version: '3'

services: 
    web:
        build: .
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 7000:7000
        environment:
            - PORT=7000